//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dict
    {
        public string DictCode { get; set; }
        public string TypeCode { get; set; }
        public string DictName { get; set; }
        public Nullable<int> DictOrder { get; set; }
    
        public virtual DictType DictType { get; set; }
    }
}
