//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductClass()
        {
            this.ProductClass_Supplier = new HashSet<ProductClass_Supplier>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string ClassIntro { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductClass_Supplier> ProductClass_Supplier { get; set; }
    }
}
