//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrder()
        {
            this.Order_Product = new HashSet<Order_Product>();
            this.ProductPresencenOrder = new HashSet<ProductPresencenOrder>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> OrderToTime { get; set; }
        public string Remark { get; set; }
        public string AuditRemark { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string OrderState { get; set; }
        public string AuditUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPresencenOrder> ProductPresencenOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
