//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageLocation
    {
        public int StorageLocationID { get; set; }
        public Nullable<int> StorageRegionID { get; set; }
        public string StorageLocationCode { get; set; }
        public string StorageLocationNo { get; set; }
        public Nullable<int> MaxVolume { get; set; }
        public string StorageState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserName { get; set; }
    
        public virtual StorageRegion StorageRegion { get; set; }
    }
}
